spring.application.name=train

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ecommerce_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=SilentRiver@Beach#42

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
